arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
# Other config...
synthetic-package: false
output-dir: lib/l10n
# use-escaping: true
# nullable-getter: false