name: moonlight
description: "moonlight framework"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  http: ^1.4.0
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  # storage
  shared_preferences: ^2.5.3
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.4
  firebase_remote_config: ^5.4.3
  # database
  hive_flutter: ^1.1.0
  sqflite: ^2.4.2
  # notification
  flutter_local_notifications: ^19.2.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  # earning
  google_mobile_ads: ^6.0.0
  # UI
  youtube_player_flutter: ^9.1.1
  # localizations
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_gen: ^5.10.0
  geolocator: ^14.0.0
  # Framework / State Management
  provider: ^6.1.5
  get: ^4.7.2
  flutter_bloc: ^9.1.1
  sensors_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true # Generate code with intl_translation
  assets:
    - assets/images/
    - assets/json/
