name: moonlight
description: moonlight framework.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^4.0.1
  dio: ^5.2.1+1
  firebase_core: ^2.15.0
  firebase_remote_config: ^4.2.3
  flutter_local_notifications: ^14.1.1
  google_mobile_ads: ^3.0.0
  http: ^1.0.0
  share_plus: ^7.0.2
  shared_preferences: ^2.1.2
  sqflite: ^2.2.8+4
  url_launcher: ^6.1.11
  youtube_player_flutter: ^8.1.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
