name: moonlight
description: "moonlight framework"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^10.1.3
  url_launcher: ^6.3.1
  http: ^1.2.2
  dio: ^5.7.0
  connectivity_plus: ^6.1.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  # storage
  shared_preferences: ^2.3.4
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.4
  firebase_remote_config: ^5.2.0
  # database
  hive_flutter: ^1.1.0
  sqflite: ^2.4.1
  # notification
  flutter_local_notifications: ^18.0.1
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  # earning
  google_mobile_ads: ^5.2.0
  # UI
  youtube_player_flutter: ^9.1.1
  # localizations
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_gen: ^5.8.0
  geolocator: ^13.0.2
  # Framework / State Management
  provider: ^6.1.2
  get: ^4.6.6
  flutter_bloc: ^8.1.6  
  sensors_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true # Generate code with intl_translation
  assets:
    - assets/images/
    - assets/json/
